### ISSUE TITLE
Support for to_plain_text

### ISSUE THREAD

**Issue by williamkennedy** [afomera/richer_text#11]
ActionText has a method called `to_plain_text` https://github.com/rails/rails/blob/0d30e84878223df68efda3b0e1741611d9682a45/actiontext/lib/action_text/content.rb#L129

I think it would be good to add this `RicherText::JsonText`

I have to investigate more but it seems we can take advantage of Rails here

```
module RicherText
  class JsonText < ApplicationRecord
    .....
    def to_s
      RicherText.default_renderer.visit(document)
    end

    def to_plain_text
      ActionText::Content.new(to_s).to_plain_text
    end

```

Happy to add this myself.

**Comment by afomera** [comment]
I completely agree re: the need for a plain text method @williamkennedy, 

I'd prefer to not use ActionText::Content further in the gem, and instead prefer the visitor pattern for allowing us to traverse the JSON nodes.

I honestly meant to add this before release but I forgot since I didn't write this down.

I haven't tested this, but something like this was what I was imagining, and then we'd have a `default_text_renderer` config option (like the `default_renderer` option), that'd default to this class below.

```ruby
module RicherText
  class TextVisitor
    def visit(node)
      node.accept(self)
    end

    def visit_attachment_figure(node)
      visit_children(node).join
    end

    def visit_attachment_gallery(node)
      visit_children(node).join
    end

    def visit_blockquote(node)
      visit_children(node).join
    end

    def visit_bullet_list(node)
      visit_children(node).join
    end

    def visit_callout(node)
      visit_children(node).join
    end

    def visit_children(node)
      node.children.map { |child| visit(child) }.join(" ")
    end

    def visit_code_block(node)
    end

    def visit_doc(node)
      visit_children(node).join
    end

    def visit_iframely_embed(node)
    end

    def visit_mention(node, _marks)
      node.name
    end

    def visit_paragraph(node)
      visit_children(node).join
    end

    def visit_richer_text_embed(node)
    end

    def visit_list_item(node)
      visit_children(node).join
    end

    def visit_ordered_list(node)
      visit_children(node).join
    end

    def visit_heading(node)
      visit_children(node).join
    end

    def visit_hard_break(_node)
    end

    def visit_horizontal_rule(_node)
    end

    def visit_image(_node)
    end

    def visit_text(node, _marks)
      node.text
    end

    def visit_table(node)
      visit_children(node).join
    end

    def visit_table_row(node)
      visit_children(node).join
    end

    def visit_table_cell(node)
      visit_children(node).join
    end

    def visit_table_header(node)
      visit_children(node).join
    end
  end
end
```


note that we probably will need to add a sanitizer onto the text content after it's all joined (up in `visit_children` makes sense to me, and there could def be some code cleanup here I'm sure.

This is bigger than what change you proposed so if you don't want to try and tackle this, that's okay just let me know 👍  

Thank you!

**Comment by afomera** [comment]
cc @williamkennedy I got sidetracked this weekend, and decided to put up my idea in a PR, if you want to try it out and see how it works for you. https://github.com/afomera/richer_text/pull/12

I'll merge this soon.

**Comment by williamkennedy** [comment]
Thanks @afomera 

Another thing that I thought of was adding some tests so it's easier to contribute.
