### ISSUE TITLE
Failed to resolve module specifier "@afomera/richer-text"

### ISSUE THREAD

**Issue by etmartinkazoo** [afomera/richer_text#9]
I am using:
Ruby 3.3.1
Rails 7.1.3.2

I am following the "Installation" docs on the Richer Text site but getting the following error: `Uncaught TypeError: Failed to resolve module specifier "@afomera/richer-text". Relative references must start with either "/", "./", or "../".`

It is very possible that I am missing something obvious. Any assistance would be appreciated.

Thank you for your work on this great project!

**Comment by afomera** [comment]
Hi @etmartinkazoo, could you share more about your JavaScript setup in your project?  Those Rails and Ruby versions look good to go from the Ruby side of things, but there may be an issue on the JS side of things with some bundlers.

I'm thinking things won't work with Richer Text if import maps are used, due to some compatibility issues I haven't been able to work out, but I haven't quite seen this error before.

I've tested using esbuild in my project, but haven't had a chance to checkout other bundlers, so maybe there's an issue there?

**Comment by afomera** [comment]
I just released alpha.7 today of RicherText.js which completely rewrites the bundler I use under the hood to try and help resolve issues.

Perhaps give that a go and see if there's any luck?

**Comment by etmartinkazoo** [comment]
Hi @afomera - Apologies, I have been away for a few days. I will give this a try. Thank you!

**Comment by etmartinkazoo** [comment]
Hi @afomera - My issues have been resolved with the newest version. Thank you for a great gem!

**Comment by afomera** [comment]
Awesome thanks @etmartinkazoo! Glad to hear it and do let me know if you have suggestions or any further issues :)
